name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    uses: platform-mesh/.github/.github/workflows/job-node-test.yml@33d3ee309a70b300c1775d78054cbb9215673b7b
    secrets: inherit # zizmor: ignore[secrets-inherit]

  docker-build:
    uses: platform-mesh/.github/.github/workflows/job-docker-build.yml@33d3ee309a70b300c1775d78054cbb9215673b7b
    with:
      imageTagName: ghcr.io/platform-mesh/portal

  quality-gate:
    if: always()
    permissions: {}
    needs: [test, docker-build]
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check results
        env:
          TEST_RESULT: ${{ needs.test.result }}
          DOCKER_BUILD_RESULT: ${{ needs.docker-build.result }}
        run: |
          if [[ "${TEST_RESULT}" != "success" ]]; then
            echo "test failed"
            exit 1
          fi
          if [[ "${DOCKER_BUILD_RESULT}" != "success" ]]; then
            echo "docker-build failed"
            exit 1
          fi
