name: pipe
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipe:
    uses: platform-mesh/.github/.github/workflows/pipeline-node-app.yml@93ad0ac2cf56755dfd602528f3103f9abfa967f4 # main
    secrets: inherit
    with:
      imageTagName: ghcr.io/platform-mesh/portal
      componentVersionKey: portal
